# Generated by Django 2.2.1 on 2019-05-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostfound',
            name='where',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
