# Generated by Django 2.2.1 on 2019-05-12 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Create',
            new_name='Publicity',
        ),
    ]
