# Generated by Django 2.2.1 on 2019-05-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0002_auto_20190513_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicity',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
